// Generated by tools/render-props.py — do not edit by hand.
// mac: rendered from the .glb with Blender (OPTIX), camera az 0.0 el 6.0 lens 50.0mm,
// cropped to the object and its shadow. Sizes in pixels; `screen` is the box round the screen, as fractions
// of the picture. `close` is the same picture at three times the size, the part round the screen only
// (--close): where it sits in the wide picture, as fractions, and where the screen sits in it.
export const MAC = {
  src: '/program/mac.webp',
  width: 2400,
  height: 1428,
  screen: { x: 0.3450, y: 0.1302, w: 0.2500, h: 0.3180 },
  close: {
    src: '/program/mac-close.webp',
    width: 3974,
    height: 3009,
    x: 0.2075, y: -0.0447, w: 0.5249, h: 0.6677,
    screen: { x: 0.2619, y: 0.2619, w: 0.4762, h: 0.4762 },
  },
} as const;
