// Generated by tools/render-props.py — do not edit by hand.
// phone: rendered from the .glb with Blender (OPTIX), camera az 70.0 el 6.0 lens 85.0mm,
// cropped to the object. Sizes in pixels.
export const PHONE = {
  src: '/hero/phone.webp',
  width: 399,
  height: 2167,
} as const;
