#!/usr/bin/env python3
"""
Build the site's display type as SVG outlines.

  WILDCARD*                      lib/wordmark.ts, public/wildcard-wordmark.svg
  *  (the asterisk alone)        app/icon.svg, the favicon
  WHO DECIDES / WHAT YOU ARE?    lib/manifesto.ts, one path per word

Source face: NimbusSanL-Bold (URW++, 1999), the GPL Helvetica clone that ships
with Ghostscript, read here from the copy Hancom Office installs. The font file
is not copied into the project; only the outlines of the glyphs the site needs
are, which the GPL font exception permits. Advance widths and pair kerning come
from the AFM beside it, and every setting is tracked by --track (1/1000 em,
negative = tighter): -30, the same for the mark and the sentence.

The manifesto is set as two lines on a shared left edge (both begin with W,
whose left side bearing is the same, so origin and ink align). Each word is its
own path so the page can treat one on its own: DECIDES can leave, and a rule
the weight of the typeface's underscore, drawn to the width of the word and
standing on its baseline, is left in its place.

Usage:
  python tools/build-type.py [--track -30] [--leading 0.96] [--font path/to/n019004l.pfb]
"""
import argparse
import json
from pathlib import Path

from fontTools.afmLib import AFM
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.t1Lib import T1Font

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_FONT = Path(r"C:\Program Files (x86)\Hnc\Common80\ImgFilters\GS\fonts\n019004l.pfb")

WORDMARK = "WILDCARD*"
MANIFESTO = ["WHO DECIDES WHAT YOU ARE?"]  # one line, over the film's last frame
BLANK = ("DECIDES", 0)  # the word that can leave, and its line

# The film's captions, in the film's own time (WORKS/2026-09_wildcard-dreams/out/dreams-1080.mp4):
# from the cut list and a word-level transcript of each shot, with a little air around each line.
CAPTIONS = [
    (0.3, 3.3, "So, what do you need? Besides a miracle."),
    (5.2, 7.0, "Dreams."),
    (7.45, 10.3, "Lots of dreams."),
    (25.1, 28.1, "No one has ever done anything like this."),
    (30.7, 33.4, "That's why it's going to work."),
]
# Every caption shares one vertical box, from a little above the capitals to the
# descender line, so the lines sit on one baseline at one CSS height.
CAPTION_TOP, CAPTION_BOTTOM = -760, 220

GLYPH_NAMES = {"*": "asterisk", " ": "space", "?": "question", "_": "underscore",
               ",": "comma", ".": "period", "'": "quoteright"}
INK = "#0a0b0d"
PAPER = "#f2f4f7"


def ntos(v: float) -> str:
    s = f"{v:.1f}"
    return s.rstrip("0").rstrip(".") if "." in s else s


class Face:
    def __init__(self, path: Path):
        self.afm = AFM(str(path.with_suffix(".afm")))
        self.glyphs = T1Font(str(path)).getGlyphSet()

    @staticmethod
    def name(ch: str) -> str:
        return GLYPH_NAMES.get(ch, ch)

    def width(self, name: str) -> float:
        return self.afm[name][1]  # (code, width, bbox)

    def kern(self, a: str, b: str) -> float:
        return self.afm[(a, b)] if self.afm.has_kernpair((a, b)) else 0

    def bbox(self, name: str):
        return self.afm[name][2]


def layout(face: Face, text: str, track: float):
    """[(char, glyph, x)] with AFM advances, AFM pair kerning and tracking."""
    placed, x, prev, kerns = [], 0.0, None, []
    for ch in text:
        name = face.name(ch)
        if prev is not None:
            k = face.kern(prev, name)
            if k:
                kerns.append(f"{prev}{name}:{ntos(k)}")
            x += k + track
        placed.append((ch, name, x))
        x += face.width(name)
        prev = name
    return placed, kerns


def ink_bounds(face: Face, placed, baseline=0.0):
    pen = BoundsPen(face.glyphs)
    for _, name, x in placed:
        face.glyphs[name].draw(TransformPen(pen, (1, 0, 0, -1, x, baseline)))
    return pen.bounds  # (x0, y0, x1, y1), SVG y-down


def outline(face: Face, placed, dx=0.0, baseline=0.0):
    parts = []
    for _, name, x in placed:
        pen = SVGPathPen(face.glyphs, ntos=ntos)
        face.glyphs[name].draw(TransformPen(pen, (1, 0, 0, -1, x + dx, baseline)))
        parts.append(pen.getCommands())
    return " ".join(p for p in parts if p)


def union(boxes):
    boxes = [b for b in boxes if b]
    return (min(b[0] for b in boxes), min(b[1] for b in boxes), max(b[2] for b in boxes), max(b[3] for b in boxes))


# ── the wordmark and the favicon ─────────────────────────────────────────────

def build_wordmark(face: Face, track: float):
    placed, kerns = layout(face, WORDMARK, track)
    x0, y0, x1, y1 = ink_bounds(face, placed)
    w, h = x1 - x0, y1 - y0
    d = outline(face, placed, -x0, -y0)

    (ROOT / "lib" / "wordmark.ts").write_text(
        "// Generated by tools/build-type.py — do not edit by hand.\n"
        f"// Face: NimbusSanL-Bold (URW++). AFM pair kerning, tracking {ntos(track)}/1000 em.\n"
        "// The viewBox is tight to the ink, so a CSS width is the width of the letters.\n"
        "export const WORDMARK = {\n"
        f"  text: {json.dumps(WORDMARK)},\n"
        f"  viewBox: '0 0 {ntos(w)} {ntos(h)}',\n"
        f"  width: {ntos(w)},\n"
        f"  height: {ntos(h)},\n"
        "  /** width / height: the CSS derives the mark's height from its width with this. */\n"
        f"  aspect: {w / h:.4f},\n"
        f"  path: {json.dumps(d)},\n"
        "} as const;\n",
        encoding="utf-8",
    )
    (ROOT / "public" / "wildcard-wordmark.svg").write_text(
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {ntos(w)} {ntos(h)}">'
        f"<title>{WORDMARK}</title>"
        f'<path fill="currentColor" d="{d}"/></svg>\n',
        encoding="utf-8",
    )

    star = [("*", "asterisk", 0.0)]
    sx0, sy0, sx1, sy1 = ink_bounds(face, star)
    sw, sh = sx1 - sx0, sy1 - sy0
    size, fill = 256, 0.56
    scale = size * fill / max(sw, sh)
    tx, ty = (size - sw * scale) / 2, (size - sh * scale) / 2
    sd = outline(face, star, -sx0, -sy0)
    (ROOT / "app" / "icon.svg").write_text(
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {size} {size}">'
        f'<rect width="{size}" height="{size}" fill="{INK}"/>'
        f'<path fill="{PAPER}" transform="translate({ntos(tx)} {ntos(ty)}) scale({scale:.4f})" d="{sd}"/>'
        "</svg>\n",
        encoding="utf-8",
    )
    print(f"wordmark   {ntos(w)} x {ntos(h)}  aspect {w / h:.4f}  kerning {', '.join(kerns) or 'none'}")


# ── the manifesto ────────────────────────────────────────────────────────────

def build_manifesto(face: Face, track: float, leading: float, align: str = "left"):
    em = 1000
    lines = []
    for i, text in enumerate(MANIFESTO):
        baseline = i * leading * em
        placed, kerns = layout(face, text, track)
        # split the placed glyphs into words at the spaces
        words, cur = [], []
        for item in placed:
            if item[0] == " ":
                if cur:
                    words.append(cur)
                cur = []
            else:
                cur.append(item)
        if cur:
            words.append(cur)
        lines.append({"text": text, "baseline": baseline, "words": words, "kerns": kerns,
                      "advance": placed[-1][2] + face.width(placed[-1][1])})

    # Right alignment: every line's ink ends on the same edge. A shorter line
    # is shifted right by the difference of the lines' ink widths.
    if align == "right":
        rights = [ink_bounds(face, [g for w in l["words"] for g in w], l["baseline"])[2] for l in lines]
        for l, r in zip(lines, rights):
            shift = max(rights) - r
            l["words"] = [[(c, n, x + shift) for c, n, x in w] for w in l["words"]]

    # The blank: a rule the weight of the typeface's own underscore, as wide as
    # the ink of the word it replaces, standing on the baseline like the line
    # on a form. At the underscore's own depth (120–189 below the baseline) it
    # nearly touched the capitals of the line below.
    word, line_no = BLANK
    line = lines[line_no]
    target = next(w for w in line["words"] if "".join(c for c, _, _ in w) == word)
    bx0, by0, bx1, by1 = ink_bounds(face, target, line["baseline"])
    _, u_lly, _, u_ury = face.bbox("underscore")
    weight = u_ury - u_lly
    blank = (bx0, line["baseline"] - weight, bx1, line["baseline"])

    box = union([ink_bounds(face, [g for w in l["words"] for g in w], l["baseline"]) for l in lines] + [blank])
    x0, y0, x1, y1 = box
    W, H = x1 - x0, y1 - y0

    out_lines = []
    for l in lines:
        out_words = []
        for w in l["words"]:
            text = "".join(c for c, _, _ in w)
            out_words.append({"text": text, "d": outline(face, w, -x0, l["baseline"] - y0)})
        out_lines.append({"text": l["text"], "words": out_words})

    hit_top = lines[line_no]["baseline"] - face.bbox("D")[3] - y0  # cap height above the baseline
    blank_out = {
        "word": word,
        "line": line_no,
        "x": round(blank[0] - x0, 1),
        "y": round(blank[1] - y0, 1),
        "width": round(blank[2] - blank[0], 1),
        "height": round(blank[3] - blank[1], 1),
        # the word's own box down to the bottom of the blank: what the pointer rests on
        "hit": {
            "x": round(bx0 - x0, 1),
            "y": round(hit_top, 1),
            "width": round(bx1 - bx0, 1),
            "height": round(blank[3] - y0 - hit_top, 1),
        },
    }

    (ROOT / "lib" / "manifesto.ts").write_text(
        "// Generated by tools/build-type.py — do not edit by hand.\n"
        f"// Face: NimbusSanL-Bold (URW++). AFM pair kerning, tracking {ntos(track)}/1000 em,\n"
        f"// baselines {leading} em apart. One path per word; viewBox tight to the ink.\n"
        "export const MANIFESTO = {\n"
        f"  text: {json.dumps(' '.join(MANIFESTO))},\n"
        f"  align: {json.dumps(align)},\n"
        f"  viewBox: '0 0 {ntos(W)} {ntos(H)}',\n"
        f"  width: {ntos(W)},\n"
        f"  height: {ntos(H)},\n"
        f"  aspect: {W / H:.4f},\n"
        f"  lines: {json.dumps(out_lines, ensure_ascii=False)},\n"
        "  /** Where the typeface's underscore is drawn when DECIDES leaves, and the box the pointer rests on. */\n"
        f"  blank: {json.dumps(blank_out)},\n"
        "} as const;\n",
        encoding="utf-8",
    )
    for l in lines:
        print(f"manifesto  {l['text']!r:18} advance {ntos(l['advance'])}  kerning {', '.join(l['kerns']) or 'none'}")
    print(f"manifesto  block {ntos(W)} x {ntos(H)}  aspect {W / H:.4f}  blank {blank_out['width']} x {blank_out['height']}")


def build_captions(face: Face, track: float):
    cues = []
    for start, end, text in CAPTIONS:
        placed, _ = layout(face, text, track)
        glyphs = [g for g in placed if g[0] != " "]
        x0, _, x1, _ = ink_bounds(face, glyphs, 0)
        d = outline(face, glyphs, -x0, -CAPTION_TOP)  # baseline sits at y = -CAPTION_TOP
        cues.append({"start": start, "end": end, "text": text,
                     "viewBox": f"0 0 {ntos(x1 - x0)} {CAPTION_BOTTOM - CAPTION_TOP}", "d": d})
    (ROOT / "lib" / "captions.ts").write_text(
        "// Generated by tools/build-type.py — do not edit by hand.\n"
        f"// The film's captions as outlines: NimbusSanL-Bold (URW++), AFM pair kerning, tracking {ntos(track)}/1000 em.\n"
        "// Times are the film's (out/dreams-1080.mp4). Every viewBox is the same height, baseline at\n"
        f"// {-CAPTION_TOP} of {CAPTION_BOTTOM - CAPTION_TOP}, so one CSS height sets them all on one baseline.\n"
        "export type Cue = { start: number; end: number; text: string; viewBox: string; d: string };\n\n"
        f"export const CAPTIONS: readonly Cue[] = {json.dumps(cues, ensure_ascii=False, indent=2)};\n",
        encoding="utf-8",
    )
    print(f"captions   {len(cues)} lines, box height {CAPTION_BOTTOM - CAPTION_TOP}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--font", type=Path, default=DEFAULT_FONT)
    ap.add_argument("--track", type=float, default=-30)
    ap.add_argument("--leading", type=float, default=0.96, help="baseline to baseline, in em")
    ap.add_argument("--align", choices=["left", "right"], default="left", help="manifesto lines on a shared left edge or a shared right edge")
    args = ap.parse_args()

    face = Face(args.font)
    build_wordmark(face, args.track)
    build_manifesto(face, args.track, args.leading, args.align)
    build_captions(face, 0)  # text size: the face's own spacing


if __name__ == "__main__":
    main()
